version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vimeo_clone
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./react-frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

volumes:
  pgsql-data:
  redis-data:
